### ISSUE TITLE
H265 compile?

### ISSUE THREAD

**Issue by kkm** [nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#22]
Hi,

Is that possible?

**Comment by vzamanillo** [comment]
Hi kkm!

You can play with the proprietary [codecs patch](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/tree/master/patch) to add your desired decoder, demuxer or parser, then you could build your custom library using the `-pc` switch.

**Comment by kkm** [comment]
thanks but I did try with your guide windows on cygwin.
I dont understand why I cant comile in cygwin.

![capturei_2016127_12-45-13](https://cloud.githubusercontent.com/assets/134290/20966538/17241ecc-bc7b-11e6-9d0a-48d46674c077.png)

**Comment by vzamanillo** [comment]
Could you please check your python installation with

`user@host:~$ which python`

from Cygwin console?

**Comment by kkm** [comment]
> $ which python
/cygdrive/c/Python27/python

what windows version did you try? mine is win10 and 64bit

**Comment by vzamanillo** [comment]
Try installing the python package on Cygwin and run the script with it.

**Comment by kkm** [comment]
I uninstall python from windows and install python on official cygwin.
So I get the error message. And I hope you can fix for me.

![capturei_2016128_7-50-47](https://cloud.githubusercontent.com/assets/134290/21000418/0a006822-bd1b-11e6-91dc-75c5650252f7.png)

**Comment by ghostoy** [comment]
@kkm As described in Google's doc https://www.chromium.org/developers/how-tos/install-depot-tools:

> Chromium is mostly designed to be run using the native Windows tools and the Msys (Git for Windows) toolchain. Cygwin is not recommended, and likely things will fail in cryptic ways.

**Comment by kkm** [comment]
Okay and I believe the url is incorrect.

Above screenshot says:
> CalledProcessError: Command 'gclient config --unmanaged --name=src https://github.com/nwjs/chromium.src.git@tags/nw-v0.19.0' returned non-zero exit status 2

Look the url https://github.com/nwjs/chromium.src.git@tags/nw-v0.19.0 doesnt exists.

**Comment by kkm** [comment]
>File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'gclient config --unmanaged --name=src https://github.com/nwjs/chromium.src.git@tags/nw-v0.19.0' returned non-zero exit status 2

I believe url is incorrect https://github.com/nwjs/chromium.src.git@tags/nw-v0.19.0
and the guide from here says cygwin to use.

**Comment by ghostoy** [comment]
@kkm I think the guide means Cygwin may **appear** to work, but actually failed to install 3rd party tools in the end.

On Windows, Chromium and ffmpeg are built with VS tool chain. You can't simply use tools in Cygwin to build it.

So do not use Cygwin.

The URL is correct and it should be the same URL used to build ffmpeg in this project.

**Comment by kkm** [comment]
Yeah I finally made it.

1. install python2.7 on cygwin package
2. Download depot_tools from google chromium and seperate folder in the start of PATH.
then follow guide of here
3. build_ffmpeg_proprietary_codecs.patch doesnt work and I get error http://capturei.tikatoy.com/RDrw but I edit a bit patch then works finally..
https://gist.github.com/kkm/7c30aa8eb124c2ce9aee6f4d36be7176

**Comment by vzamanillo** [comment]
@ghostoy, I did a build without problems for 18.x on Windows using Cygwin, but maybe the script is outdated due to some Google changes, I will take a look to fix it PRs are welcome too. Thank you all for helping us.

**Comment by kkm** [comment]
@vzamanillo can you test for me? I can play from http://www.h265files.com/embed-h265-video.php h265 and .flv on <video>

I believe I need more tweak in chrome?
![capturei_20161211_0-39-27](https://cloud.githubusercontent.com/assets/134290/21076943/5f37119e-bf3a-11e6-851b-eca13eee2986.png)

**Comment by kkm** [comment]
I did try https://tools.woolyss.com/html5-audio-video-tester/?u=www.cinemartin.com/cinec/_Sample_Videos/Hoid/Cinemartin_A001_C001_1008BA_2_H265_HEVC_RQ.mp4

this site can you test if you can play with hevc with custom ffmpeg compile. please test for  me.

**Comment by sica07** [comment]
I can confirm the issue. I get (almost) the same error:
```
$ python build_ffmpeg.py -pc
INFO: Building ffmpeg for 0.19.2 on win for x64, proprietary_codecs = True
Creating /cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build directory...
WARNING: /cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build directory already exists, skipping...
INFO: Cleaning output directory...
INFO: Creating .gclient file...
INFO: Cloning Chromium source code for nw-0.19.2 in /cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build
fatal: destination path 'src' already exists and is not an empty directory.
INFO: Hard source code reset to nw 0.19.2 specified version
HEAD is now at 8444c47 nwjs master
INFO: Cleaning previous DEPS and BUILD.gn backup files...
INFO: Backing up and overwriting DEPS...
INFO: Backing up and overwriting BUILD.gn...
INFO: Syncing with gclient...
.gclient file in parent directory /cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build might not be the file you want to use
Syncing projects: 100% (5/5), done.

________ running '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'

________ running '/usr/bin/python src/build/mac_toolchain.py' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'

________ running '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s src/buildtools/win/gn.exe.sha1' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'
0> Downloading src/buildtools/win/gn.exe...
Success!
Downloading 1 files took 36.145952 second(s)
Hook 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s src/buildtools/win/gn.exe.sha1' took 36.64 secs

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s src/buildtools/mac/gn.sha1' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'
The current platform doesn't match "darwin", skipping.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'
The current platform doesn't match "linux*", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-libcpp -s src/third_party/libc++-static/libc++.a.sha1' in '/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build'
The current platform doesn't match "darwin", skipping.
INFO: Building ffmpeg with proprietary codecs...
INFO: Starting build...
System information:
Host OS       : win
Target OS     : win
Host arch     : x64
Target arch   : x64
Parallel jobs : 4

Chromium configure/build:
Running ['/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/configure', '--disable-everything', '--disable-all', '--disable-doc', '--disable-htmlpages', '--disable-manpages', '--disable-podpages', '--disable-txtpages', '--disable-static', '--enable-avcodec', '--enable-avformat', '--enable-avutil', '--enable-fft', '--enable-rdft', '--enable-static', '--disable-bzlib', '--disable-error-resilience', '--disable-iconv', '--disable-lzo', '--disable-network', '--disable-schannel', '--disable-sdl', '--disable-symver', '--disable-xlib', '--disable-zlib', '--disable-securetransport', '--disable-d3d11va', '--disable-dxva2', '--disable-vaapi', '--disable-vda', '--disable-vdpau', '--disable-videotoolbox', '--enable-decoder=vorbis', '--enable-decoder=pcm_u8,pcm_s16le,pcm_s24le,pcm_s32le,pcm_f32le', '--enable-decoder=pcm_s16be,pcm_s24be,pcm_mulaw,pcm_alaw', '--enable-demuxer=ogg,matroska,wav', '--enable-parser=opus,vorbis', '--optflags="-O2"', '--enable-decoder=theora,vp8', '--enable-parser=vp3,vp8', '--toolchain=msvc', '--cpu=opteron', '--enable-yasm', '--extra-cflags=-I/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/chromium/include/win', '--cc=cygwin-wrapper cl', '--ld=cygwin-wrapper link', '--nm=cygwin-wrapper dumpbin -symbols', '--ar=cygwin-wrapper lib']
cygwin-wrapper cl is unable to create an executable file.
If cygwin-wrapper cl is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
Traceback (most recent call last):
  File "./chromium/scripts/build_ffmpeg.py", line 648, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./chromium/scripts/build_ffmpeg.py", line 613, in main
    configure_args)
  File "./chromium/scripts/build_ffmpeg.py", line 605, in do_build_ffmpeg
    options.config_only, branding, configure_flags)
  File "./chromium/scripts/build_ffmpeg.py", line 211, in BuildFFmpeg
    [os.path.join(FFMPEG_DIR, 'configure')] + configure_flags, cwd=config_dir)
  File "./chromium/scripts/build_ffmpeg.py", line 95, in PrintAndCheckCall
    subprocess.check_call(argv, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/configure', '--disable-everything', '--disable-all', '--disable-doc', '--disable-htmlpages', '--disable-manpages', '--disable-podpages', '--disable-txtpages', '--disable-static', '--enable-avcodec', '--enable-avformat', '--enable-avutil', '--enable-fft', '--enable-rdft', '--enable-static', '--disable-bzlib', '--disable-error-resilience', '--disable-iconv', '--disable-lzo', '--disable-network', '--disable-schannel', '--disable-sdl', '--disable-symver', '--disable-xlib', '--disable-zlib', '--disable-securetransport', '--disable-d3d11va', '--disable-dxva2', '--disable-vaapi', '--disable-vda', '--disable-vdpau', '--disable-videotoolbox', '--enable-decoder=vorbis', '--enable-decoder=pcm_u8,pcm_s16le,pcm_s24le,pcm_s32le,pcm_f32le', '--enable-decoder=pcm_s16be,pcm_s24be,pcm_mulaw,pcm_alaw', '--enable-demuxer=ogg,matroska,wav', '--enable-parser=opus,vorbis', '--optflags="-O2"', '--enable-decoder=theora,vp8', '--enable-parser=vp3,vp8', '--toolchain=msvc', '--cpu=opteron', '--enable-yasm', '--extra-cflags=-I/cygdrive/c/Users/Marius/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/chromium/include/win', '--cc=cygwin-wrapper cl', '--ld=cygwin-wrapper link', '--nm=cygwin-wrapper dumpbin -symbols', '--ar=cygwin-wrapper lib']' returned non-zero exit status 1
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 96, in main
    check_build_with_proprietary_codecs(proprietary_codecs, host_platform, target_arch)
  File "build_ffmpeg.py", line 480, in check_build_with_proprietary_codecs
    subprocess.check_call('./chromium/scripts/build_ffmpeg.py {0} {1}'.format(host_platform, target_arch), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command './chromium/scripts/build_ffmpeg.py win x64' returned non-zero exit status 1
```

**Comment by vzamanillo** [comment]
@sica07 that issue is not related to the builder script, is related to a compiler error.

**Comment by sica07** [comment]
@vzamanillo thanks for the quick response. I'll try to figure it out and I'll announce if it will work (I really hope it will).

**Comment by vzamanillo** [comment]
@kkm, Did you test with a custom NW.js build enabling the hevc demuxer?

@sica07, check the `build/src/third_party/ffmpeg/chromium/scripts/build.arch.host/` for a `config.log` open it an look for the last error.

**Comment by sica07** [comment]
@vzamanillo there is no such directory inside the scripts folder:
```
ls -al build/src/third_party/ffmpeg/chromium/scripts/
total 133
drwxrwxr-x+ 1 Marius Marius     0 dec.  13 20:18 .
drwxrwxr-x+ 1 Marius Marius     0 dec.  13 20:18 ..
-rwxrwxr-x+ 1 Marius Marius 22611 dec.  13 20:18 build_ffmpeg.py
-rwxrwxr-x+ 1 Marius Marius  1046 dec.  13 20:18 copy_config.sh
-rwxrw-r--+ 1 Marius Marius 15903 dec.  13 20:18 credits_updater.py
-rwxrwxr-x+ 1 Marius Marius  7397 dec.  13 20:18 credits_updater_unittest.py
-rwxrwxr-x+ 1 Marius Marius  2436 dec.  13 20:18 cygwin-wrapper
-rwxrw-r--+ 1 Marius Marius   252 dec.  13 20:18 enum.py
-rwxrwxr-x+ 1 Marius Marius 31751 dec.  13 20:18 generate_gn.py
-rwxrwxr-x+ 1 Marius Marius 17811 dec.  13 20:18 generate_gn_unittest.py
-rwxrwxr-x+ 1 Marius Marius  1099 dec.  13 20:18 generate_libs.py
drwxrwxr-x+ 1 Marius Marius     0 dec.  13 20:18 license_texts
-rwxrwxr-x+ 1 Marius Marius   800 dec.  13 20:18 munge_config_optimizations.sh
-rwxrwxr-x+ 1 Marius Marius  3044 dec.  13 20:18 win_env.sh
```

**Comment by vzamanillo** [comment]
Seems like you missed some step configuring the build enviromnent.

**Comment by sica07** [comment]
I'll try it again tomorrow. Thank you for all the help!

**Comment by kkm** [comment]
@vzamanillo I didnt know before about custom nwjs. I found e.g https://github.com/butterproject/nwjs-build/blob/master/build_linux64.sh#L69
I will try next year.

Thanks.

**Comment by vzamanillo** [comment]
@kkm, I think that codebase is outdated. You need the same codebase, in this case 19.x
